/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { InventoryItem } from "./InventoryItem";
import { InventoryItemCountArgs } from "./InventoryItemCountArgs";
import { InventoryItemFindManyArgs } from "./InventoryItemFindManyArgs";
import { InventoryItemFindUniqueArgs } from "./InventoryItemFindUniqueArgs";
import { CreateInventoryItemArgs } from "./CreateInventoryItemArgs";
import { UpdateInventoryItemArgs } from "./UpdateInventoryItemArgs";
import { DeleteInventoryItemArgs } from "./DeleteInventoryItemArgs";
import { DamageReportFindManyArgs } from "../../damageReport/base/DamageReportFindManyArgs";
import { DamageReport } from "../../damageReport/base/DamageReport";
import { ExpiryReportFindManyArgs } from "../../expiryReport/base/ExpiryReportFindManyArgs";
import { ExpiryReport } from "../../expiryReport/base/ExpiryReport";
import { InventoryItemService } from "../inventoryItem.service";
@graphql.Resolver(() => InventoryItem)
export class InventoryItemResolverBase {
  constructor(protected readonly service: InventoryItemService) {}

  async _inventoryItemsMeta(
    @graphql.Args() args: InventoryItemCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [InventoryItem])
  async inventoryItems(
    @graphql.Args() args: InventoryItemFindManyArgs
  ): Promise<InventoryItem[]> {
    return this.service.inventoryItems(args);
  }

  @graphql.Query(() => InventoryItem, { nullable: true })
  async inventoryItem(
    @graphql.Args() args: InventoryItemFindUniqueArgs
  ): Promise<InventoryItem | null> {
    const result = await this.service.inventoryItem(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => InventoryItem)
  async createInventoryItem(
    @graphql.Args() args: CreateInventoryItemArgs
  ): Promise<InventoryItem> {
    return await this.service.createInventoryItem({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => InventoryItem)
  async updateInventoryItem(
    @graphql.Args() args: UpdateInventoryItemArgs
  ): Promise<InventoryItem | null> {
    try {
      return await this.service.updateInventoryItem({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => InventoryItem)
  async deleteInventoryItem(
    @graphql.Args() args: DeleteInventoryItemArgs
  ): Promise<InventoryItem | null> {
    try {
      return await this.service.deleteInventoryItem(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [DamageReport], { name: "damageReports" })
  async findDamageReports(
    @graphql.Parent() parent: InventoryItem,
    @graphql.Args() args: DamageReportFindManyArgs
  ): Promise<DamageReport[]> {
    const results = await this.service.findDamageReports(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [ExpiryReport], { name: "expiryReports" })
  async findExpiryReports(
    @graphql.Parent() parent: InventoryItem,
    @graphql.Args() args: ExpiryReportFindManyArgs
  ): Promise<ExpiryReport[]> {
    const results = await this.service.findExpiryReports(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
