/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DamageReportListRelationFilter } from "../../damageReport/base/DamageReportListRelationFilter";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { ExpiryReportListRelationFilter } from "../../expiryReport/base/ExpiryReportListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";

@InputType()
class InventoryItemWhereInput {
  @ApiProperty({
    required: false,
    type: () => DamageReportListRelationFilter,
  })
  @ValidateNested()
  @Type(() => DamageReportListRelationFilter)
  @IsOptional()
  @Field(() => DamageReportListRelationFilter, {
    nullable: true,
  })
  damageReports?: DamageReportListRelationFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  expiryDate?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ExpiryReportListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ExpiryReportListRelationFilter)
  @IsOptional()
  @Field(() => ExpiryReportListRelationFilter, {
    nullable: true,
  })
  expiryReports?: ExpiryReportListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  quantity?: IntNullableFilter;
}

export { InventoryItemWhereInput as InventoryItemWhereInput };
